version: '3.0'
services:
  music-store-web:
    # Can either reference the pre-built image or build the image during creation
    # Double check why both of these can be listed in version 2+.
    image: ashleypoole/musicstore:latest
    build: .
    ports:
      - 80:80
    environment:
      - "Data:DefaultConnection:ConnectionString=Data Source=music-store-db;Database=MusicStore;User Id=sa;Password=NDC_MN_2018"
    depends_on:
      - music-store-db

  music-store-db:
    image: microsoft/mssql-server-windows-developer:2017
    ports:
      - 1433:1433
    environment:
      - sa_password=NDC_MN_2018
      - ACCEPT_EULA=Y